import type { Asset } from './types';

export const sampleAssets: Asset[] = [
  {
    id: '1',
    assetName: 'Dell XPS 15 9510',
    serialNumber: 'XPS-15-9510-A1B2',
    category: 'Laptop',
    location: 'Lagos Office - Dev Floor',
    status: 'In Use',
    assignedTo: 'John Doe',
    purchaseDate: '2023-01-15',
    condition: 'Good',
    photoUrl: 'https://placehold.co/400x400.png',
    notes: 'Excellent condition, used by senior developer.',
  },
  {
    id: '2',
    assetName: 'MacBook Pro 16" (M1)',
    serialNumber: 'MBP-M1-2021-C3D4',
    category: 'Laptop',
    location: 'Abuja Office - Design Studio',
    status: 'In Use',
    assignedTo: 'Jane Smith',
    purchaseDate: '2022-11-20',
    condition: 'New',
    photoUrl: 'https://placehold.co/400x400.png',
    notes: 'Minor scratch on the lid.',
  },
  {
    id: '3',
    assetName: 'Truenat Machine',
    serialNumber: 'TRN-001-XYZ',
    category: 'Medical Equipment',
    location: 'Central Storage',
    status: 'In Storage',
    purchaseDate: '2021-05-10',
    condition: 'Good',
    photoUrl: 'https://placehold.co/400x400.png',
  },
  {
    id: '4',
    assetName: 'GeneXpert System',
    serialNumber: 'GXP-AI-5678',
    category: 'Medical Equipment',
    location: 'Main Lab',
    status: 'For Repair',
    assignedTo: 'Lab Technician',
    purchaseDate: '2020-02-01',
    condition: 'Poor',
    photoUrl: 'https://placehold.co/400x400.png',
    notes: 'Cartridge loader is malfunctioning.',
  },
  {
    id: '5',
    assetName: 'Honda CBR Motorcycle',
    serialNumber: 'MC-HON-CBR-9981',
    category: 'Vehicle',
    location: 'Vehicle Pool',
    status: 'In Use',
    assignedTo: 'Field Officer 1',
    purchaseDate: '2023-03-22',
    condition: 'Good',
    photoUrl: 'https://placehold.co/400x400.png',
  },
   {
    id: '6',
    assetName: 'LG 27" 4K Monitor',
    serialNumber: 'LP-15-MONITOR-E5F6',
    category: 'IT Equipment',
    location: 'Lagos Office - Dev Floor',
    status: 'Disposed',
    purchaseDate: '2019-07-30',
    condition: 'Poor',
    photoUrl: 'https://placehold.co/400x400.png',
    notes: 'Screen cracked, disposed following e-waste protocol.',
  },
];
