import type { Asset } from './types';

export const sampleAssets: Asset[] = [
  {
    id: '1',
    category: 'Laptops',
    description: 'Dell XPS 15 9510',
    serialNumber: 'XPS-15-9510-A1B2',
    location: 'Lagos Office - Dev Floor',
    assignee: 'John Doe',
    verifiedStatus: 'Verified',
    verifiedDate: '2023-01-15',
    condition: 'Good',
    remarks: 'Excellent condition, used by senior developer.',
  },
  {
    id: '2',
    category: 'Laptops',
    description: 'MacBook Pro 16" (M1)',
    serialNumber: 'MBP-M1-2021-C3D4',
    location: 'Abuja Office - Design Studio',
    verifiedStatus: 'Verified',
    assignee: 'Jane Smith',
    verifiedDate: '2022-11-20',
    condition: 'New',
    remarks: 'Minor scratch on the lid.',
  },
  {
    id: '3',
    category: 'Medical Equipment',
    description: 'Truenat Machine',
    serialNumber: 'TRN-001-XYZ',
    location: 'Central Storage',
    verifiedStatus: 'Unverified',
    verifiedDate: '2021-05-10',
    condition: 'Good',
  },
  {
    id: '4',
    category: 'Medical Equipment',
    description: 'GeneXpert System',
    serialNumber: 'GXP-AI-5678',
    location: 'Main Lab',
    verifiedStatus: 'Discrepancy',
    assignee: 'Lab Technician',
    verifiedDate: '2020-02-01',
    condition: 'Poor',
    remarks: 'Cartridge loader is malfunctioning.',
  },
  {
    id: '5',
    category: 'Vehicles',
    description: 'Honda CBR Motorcycle',
    serialNumber: 'MC-HON-CBR-9981',
    location: 'Vehicle Pool',
    verifiedStatus: 'Verified',
    assignee: 'Field Officer 1',
    verifiedDate: '2023-03-22',
    condition: 'Good',
  },
   {
    id: '6',
    category: 'IT Equipment',
    description: 'LG 27" 4K Monitor',
    serialNumber: 'LP-15-MONITOR-E5F6',
    location: 'Lagos Office - Dev Floor',
    verifiedStatus: 'Verified',
    verifiedDate: '2019-07-30',
    condition: 'Poor',
    remarks: 'Screen cracked, disposed following e-waste protocol.',
  },
];
